#ifndef CASTOR_VERSION_H
#define CASTOR_VERSION_H

#define CASTOR_VERSION_MAJOR 1
#define CASTOR_VERSION_MINOR 1
#define CASTOR_VERSION_PATCH 3
#define CASTOR_VERSION "1.1.3"


#endif // CASTOR_VERSION_H
