#ifndef CASTOR_VERSION_H
#define CASTOR_VERSION_H

#define CASTOR_VERSION_MAJOR 0
#define CASTOR_VERSION_MINOR 6
#define CASTOR_VERSION_PATCH 0
#define CASTOR_VERSION "0.6.0"


#endif // CASTOR_VERSION_H
