#ifndef CASTOR_VERSION_H
#define CASTOR_VERSION_H

#define CASTOR_VERSION_MAJOR 1
#define CASTOR_VERSION_MINOR 1
#define CASTOR_VERSION_PATCH 1
#define CASTOR_VERSION "1.1.1"


#endif // CASTOR_VERSION_H
